server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1234

jpa:
  hibernate:
    ddl-auto: update

data:
  mongodb:
    host: localhost
    port: 27017
    database: stock